; generated by Slic3r 1.34.1-prusa3d-win64 on 2017-09-05 at 09:31:28

; Buse OEV5 - diamètre 0,5mm

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.40mm

M107 ; disable fan
M190 S70 ; attente chauffe plateau
M104 S195 ; préchauffe tête
G92 Z0
G1 Z5 F1200
G28 Y ; prise d'origine en Y
G28 X ; prise d'origine en X
G1 X70 Y70 F6000 ; parking
M109 S195 ; attente chauffe T0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
G1 E-3.50000 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.250 F7500.000 ; move to next layer (0)
G1 X48.319 Y50.914 F7500.000 ; move to first skirt point
G1 E3.50000 F3000.00000 ; unretract
G1 F1200
G1 X48.885 Y50.026 E3.54885 ; skirt
G1 X49.317 Y49.647 E3.57551 ; skirt
G1 X49.816 Y49.361 E3.60217 ; skirt
G1 X50.361 Y49.179 E3.62884 ; skirt
G1 X50.935 Y49.108 E3.65569 ; skirt
G1 X91.004 Y49.107 E5.51459 ; skirt
G1 X91.551 Y49.160 E5.54009 ; skirt
G1 X92.078 Y49.316 E5.56559 ; skirt
G1 X92.567 Y49.568 E5.59109 ; skirt
G1 X92.998 Y49.908 E5.61658 ; skirt
G1 X93.358 Y50.324 E5.64208 ; skirt
G1 X93.632 Y50.800 E5.66758 ; skirt
G1 X93.812 Y51.320 E5.69308 ; skirt
G1 X93.889 Y51.864 E5.71858 ; skirt
G1 X93.892 Y92.050 E7.58293 ; skirt
G1 X93.681 Y93.086 E7.63197 ; skirt
G1 X93.115 Y93.974 E7.68082 ; skirt
G1 X92.672 Y94.360 E7.70807 ; skirt
G1 X92.157 Y94.651 E7.73551 ; skirt
G1 X91.598 Y94.830 E7.76275 ; skirt
G1 X91.010 Y94.893 E7.79019 ; skirt
G1 X50.945 Y94.892 E9.64889 ; skirt
G1 X49.914 Y94.681 E9.69774 ; skirt
G1 X49.026 Y94.115 E9.74659 ; skirt
G1 X48.640 Y93.672 E9.77384 ; skirt
G1 X48.349 Y93.157 E9.80127 ; skirt
G1 X48.170 Y92.598 E9.82852 ; skirt
G1 X48.107 Y92.010 E9.85596 ; skirt
G1 X48.108 Y51.945 E11.71466 ; skirt
G1 X48.304 Y50.987 E11.76003 ; skirt
G1 E8.26003 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X50.011 Y49.762 F7500.000 ; move to first skirt point
G1 E3.50000 F3000.00000 ; unretract
G1 F1200
G1 X50.956 Y49.554 E3.54488 ; skirt
G1 X91.004 Y49.554 E5.40282 ; skirt
G1 X91.916 Y49.732 E5.44594 ; skirt
G1 X92.696 Y50.237 E5.48906 ; skirt
G1 X93.231 Y50.997 E5.53217 ; skirt
G1 X93.444 Y51.902 E5.57529 ; skirt
G1 X93.446 Y92.039 E7.43735 ; skirt
G1 X93.267 Y92.920 E7.47906 ; skirt
G1 X92.782 Y93.676 E7.52077 ; skirt
G1 X92.409 Y94.000 E7.54368 ; skirt
G1 X91.975 Y94.244 E7.56677 ; skirt
G1 X91.501 Y94.395 E7.58985 ; skirt
G1 X91.006 Y94.446 E7.61294 ; skirt
G1 X50.961 Y94.446 E9.47070 ; skirt
G1 X50.080 Y94.267 E9.51241 ; skirt
G1 X49.321 Y93.779 E9.55429 ; skirt
G1 X48.995 Y93.402 E9.57738 ; skirt
G1 X48.755 Y92.971 E9.60029 ; skirt
G1 X48.605 Y92.501 E9.62319 ; skirt
G1 X48.554 Y92.006 E9.64628 ; skirt
G1 X48.554 Y51.961 E11.50404 ; skirt
G1 X48.733 Y51.080 E11.54575 ; skirt
G1 X49.218 Y50.324 E11.58746 ; skirt
G1 X49.950 Y49.806 E11.62903 ; skirt
G1 E8.12903 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.304 Y91.304 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1200
G1 X51.696 Y91.304 E5.29109 ; perimeter
G1 X51.696 Y52.696 E7.08219 ; perimeter
G1 X90.304 Y52.696 E8.87328 ; perimeter
G1 X90.304 Y91.229 E10.66090 ; perimeter
G1 E7.16090 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.750 Y91.750 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1080
G1 X51.250 Y91.750 E5.33251 ; perimeter
G1 X51.250 Y52.250 E7.16502 ; perimeter
G1 X90.750 Y52.250 E8.99753 ; perimeter
G1 X90.750 Y91.675 E10.82656 ; perimeter
G1 X90.267 Y91.621 F7500.000 ; move inwards before travel
G1 E7.32656 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.125 Y53.780 F7500.000 ; move to first infill point
G1 E3.50000 F3000.00000 ; unretract
G1 F1200
G1 X89.421 Y53.076 E3.54632 ; infill
G1 X88.788 Y53.076 E3.57576 ; infill
G1 X89.924 Y54.212 E3.65051 ; infill
G1 X89.924 Y54.845 E3.67996 ; infill
G1 X88.155 Y53.076 E3.79635 ; infill
G1 X87.522 Y53.076 E3.82579 ; infill
G1 X89.924 Y55.478 E3.98383 ; infill
G1 X89.924 Y56.111 E4.01327 ; infill
G1 X86.889 Y53.076 E4.21295 ; infill
G1 X86.256 Y53.076 E4.24240 ; infill
G1 X89.924 Y56.744 E4.48372 ; infill
G1 X89.924 Y57.377 E4.51316 ; infill
G1 X85.623 Y53.076 E4.79613 ; infill
G1 X84.990 Y53.076 E4.82557 ; infill
G1 X89.924 Y58.010 E5.15018 ; infill
G1 X89.924 Y58.643 E5.17963 ; infill
G1 X84.357 Y53.076 E5.54587 ; infill
G1 X83.724 Y53.076 E5.57532 ; infill
G1 X89.924 Y59.276 E5.98321 ; infill
G1 X89.924 Y59.909 E6.01266 ; infill
G1 X83.091 Y53.076 E6.46219 ; infill
G1 X82.458 Y53.076 E6.49164 ; infill
G1 X89.924 Y60.542 E6.98282 ; infill
G1 X89.924 Y61.175 E7.01227 ; infill
G1 X81.825 Y53.076 E7.54509 ; infill
G1 X81.192 Y53.076 E7.57453 ; infill
G1 X89.924 Y61.808 E8.14900 ; infill
G1 X89.924 Y62.441 E8.17844 ; infill
G1 X80.559 Y53.076 E8.79455 ; infill
G1 X79.927 Y53.076 E8.82400 ; infill
G1 X89.924 Y63.073 E9.48175 ; infill
G1 X89.924 Y63.706 E9.51120 ; infill
G1 X79.294 Y53.076 E10.21059 ; infill
G1 X78.661 Y53.076 E10.24004 ; infill
G1 X89.924 Y64.339 E10.98107 ; infill
G1 X89.924 Y64.972 E11.01052 ; infill
G1 X78.028 Y53.076 E11.79320 ; infill
G1 X77.395 Y53.076 E11.82265 ; infill
G1 X89.924 Y65.605 E12.64697 ; infill
G1 X89.924 Y66.238 E12.67642 ; infill
G1 X76.762 Y53.076 E13.54238 ; infill
G1 X76.129 Y53.076 E13.57183 ; infill
G1 X89.924 Y66.871 E14.47944 ; infill
G1 X89.924 Y67.504 E14.50889 ; infill
G1 X75.496 Y53.076 E15.45814 ; infill
G1 X74.863 Y53.076 E15.48759 ; infill
G1 X89.924 Y68.137 E16.47848 ; infill
G1 X89.924 Y68.770 E16.50793 ; infill
G1 X74.230 Y53.076 E17.54047 ; infill
G1 X73.597 Y53.076 E17.56991 ; infill
G1 X89.924 Y69.403 E18.64410 ; infill
G1 X89.924 Y70.036 E18.67354 ; infill
G1 X72.964 Y53.076 E19.78937 ; infill
G1 X72.331 Y53.076 E19.81882 ; infill
G1 X89.924 Y70.669 E20.97628 ; infill
G1 X89.924 Y71.302 E21.00573 ; infill
G1 X71.698 Y53.076 E22.20484 ; infill
G1 X71.065 Y53.076 E22.23429 ; infill
G1 X89.924 Y71.935 E23.47504 ; infill
G1 X89.924 Y72.568 E23.50449 ; infill
G1 X70.432 Y53.076 E24.78689 ; infill
G1 X69.799 Y53.076 E24.81633 ; infill
G1 X89.924 Y73.201 E26.14038 ; infill
G1 X89.924 Y73.834 E26.16982 ; infill
G1 X69.166 Y53.076 E27.53551 ; infill
G1 X68.533 Y53.076 E27.56495 ; infill
G1 X89.924 Y74.467 E28.97228 ; infill
G1 X89.924 Y75.100 E29.00173 ; infill
G1 X67.900 Y53.076 E30.45070 ; infill
G1 X67.267 Y53.076 E30.48014 ; infill
G1 X89.924 Y75.733 E31.97076 ; infill
G1 X89.924 Y76.366 E32.00020 ; infill
G1 X66.634 Y53.076 E33.53246 ; infill
G1 X66.001 Y53.076 E33.56191 ; infill
G1 X89.924 Y76.999 E35.13581 ; infill
G1 X89.924 Y77.632 E35.16525 ; infill
G1 X65.368 Y53.076 E36.78080 ; infill
G1 X64.735 Y53.076 E36.81024 ; infill
G1 X89.924 Y78.265 E38.46743 ; infill
G1 X89.924 Y78.898 E38.49688 ; infill
G1 X64.102 Y53.076 E40.19570 ; infill
G1 X63.469 Y53.076 E40.22515 ; infill
G1 X89.924 Y79.531 E41.96562 ; infill
G1 X89.924 Y80.164 E41.99507 ; infill
G1 X62.836 Y53.076 E43.77719 ; infill
G1 X62.203 Y53.076 E43.80663 ; infill
G1 X89.924 Y80.797 E45.63039 ; infill
G1 X89.924 Y81.430 E45.65984 ; infill
G1 X61.570 Y53.076 E47.52524 ; infill
G1 X60.937 Y53.076 E47.55469 ; infill
G1 X89.924 Y82.063 E49.46173 ; infill
G1 X89.924 Y82.696 E49.49118 ; infill
G1 X60.304 Y53.076 E51.43987 ; infill
G1 X59.671 Y53.076 E51.46931 ; infill
G1 X89.924 Y83.329 E53.45964 ; infill
G1 X89.924 Y83.962 E53.48909 ; infill
G1 X59.038 Y53.076 E55.52106 ; infill
G1 X58.405 Y53.076 E55.55051 ; infill
G1 X89.924 Y84.595 E57.62413 ; infill
G1 X89.924 Y85.228 E57.65357 ; infill
G1 X57.772 Y53.076 E59.76884 ; infill
G1 X57.140 Y53.076 E59.79828 ; infill
G1 X89.924 Y85.860 E61.95519 ; infill
G1 X89.924 Y86.493 E61.98463 ; infill
G1 X56.507 Y53.076 E64.18318 ; infill
G1 X55.874 Y53.076 E64.21263 ; infill
G1 X89.924 Y87.126 E66.45282 ; infill
G1 X89.924 Y87.759 E66.48226 ; infill
G1 X55.241 Y53.076 E68.76410 ; infill
G1 X54.608 Y53.076 E68.79354 ; infill
G1 X89.924 Y88.392 E71.11702 ; infill
G1 X89.924 Y89.025 E71.14646 ; infill
G1 X53.975 Y53.076 E73.51158 ; infill
G1 X53.342 Y53.076 E73.54103 ; infill
G1 X89.924 Y89.658 E75.94779 ; infill
G1 X89.924 Y90.291 E75.97724 ; infill
G1 X52.709 Y53.076 E78.42565 ; infill
G1 X52.076 Y53.076 E78.45509 ; infill
G1 X89.924 Y90.924 E80.94514 ; infill
G1 X89.291 Y90.924 E80.97459 ; infill
G1 X52.076 Y53.709 E83.42299 ; infill
G1 X52.076 Y54.342 E83.45244 ; infill
G1 X88.658 Y90.924 E85.85920 ; infill
G1 X88.025 Y90.924 E85.88865 ; infill
G1 X52.076 Y54.975 E88.25377 ; infill
G1 X52.076 Y55.608 E88.28322 ; infill
G1 X87.392 Y90.924 E90.60669 ; infill
G1 X86.759 Y90.924 E90.63614 ; infill
G1 X52.076 Y56.241 E92.91797 ; infill
G1 X52.076 Y56.874 E92.94742 ; infill
G1 X86.126 Y90.924 E95.18761 ; infill
G1 X85.493 Y90.924 E95.21706 ; infill
G1 X52.076 Y57.507 E97.41561 ; infill
G1 X52.076 Y58.139 E97.44505 ; infill
G1 X84.861 Y90.924 E99.60196 ; infill
G1 X84.228 Y90.924 E99.63140 ; infill
G1 X52.076 Y58.772 E101.74666 ; infill
G1 X52.076 Y59.405 E101.77611 ; infill
G1 X83.595 Y90.924 E103.84973 ; infill
G1 X82.962 Y90.924 E103.87918 ; infill
G1 X52.076 Y60.038 E105.91115 ; infill
G1 X52.076 Y60.671 E105.94060 ; infill
G1 X82.329 Y90.924 E107.93093 ; infill
G1 X81.696 Y90.924 E107.96038 ; infill
G1 X52.076 Y61.304 E109.90907 ; infill
G1 X52.076 Y61.937 E109.93851 ; infill
G1 X81.063 Y90.924 E111.84556 ; infill
G1 X80.430 Y90.924 E111.87500 ; infill
G1 X52.076 Y62.570 E113.74041 ; infill
G1 X52.076 Y63.203 E113.76985 ; infill
G1 X79.797 Y90.924 E115.59361 ; infill
G1 X79.164 Y90.924 E115.62306 ; infill
G1 X52.076 Y63.836 E117.40518 ; infill
G1 X52.076 Y64.469 E117.43462 ; infill
G1 X78.531 Y90.924 E119.17509 ; infill
G1 X77.898 Y90.924 E119.20454 ; infill
G1 X52.076 Y65.102 E120.90337 ; infill
G1 X52.076 Y65.735 E120.93282 ; infill
G1 X77.265 Y90.924 E122.59000 ; infill
G1 X76.632 Y90.924 E122.61945 ; infill
G1 X52.076 Y66.368 E124.23500 ; infill
G1 X52.076 Y67.001 E124.26444 ; infill
G1 X75.999 Y90.924 E125.83834 ; infill
G1 X75.366 Y90.924 E125.86779 ; infill
G1 X52.076 Y67.634 E127.40005 ; infill
G1 X52.076 Y68.267 E127.42949 ; infill
G1 X74.733 Y90.924 E128.92011 ; infill
G1 X74.100 Y90.924 E128.94955 ; infill
G1 X52.076 Y68.900 E130.39852 ; infill
G1 X52.076 Y69.533 E130.42797 ; infill
G1 X73.467 Y90.924 E131.83530 ; infill
G1 X72.834 Y90.924 E131.86475 ; infill
G1 X52.076 Y70.166 E133.23043 ; infill
G1 X52.076 Y70.799 E133.25988 ; infill
G1 X72.201 Y90.924 E134.58392 ; infill
G1 X71.568 Y90.924 E134.61337 ; infill
G1 X52.076 Y71.432 E135.89576 ; infill
G1 X52.076 Y72.065 E135.92521 ; infill
G1 X70.935 Y90.924 E137.16597 ; infill
G1 X70.302 Y90.924 E137.19541 ; infill
G1 X52.076 Y72.698 E138.39453 ; infill
G1 X52.076 Y73.331 E138.42397 ; infill
G1 X69.669 Y90.924 E139.58144 ; infill
G1 X69.036 Y90.924 E139.61089 ; infill
G1 X52.076 Y73.964 E140.72671 ; infill
G1 X52.076 Y74.597 E140.75616 ; infill
G1 X68.403 Y90.924 E141.83034 ; infill
G1 X67.770 Y90.924 E141.85979 ; infill
G1 X52.076 Y75.230 E142.89233 ; infill
G1 X52.076 Y75.863 E142.92178 ; infill
G1 X67.137 Y90.924 E143.91267 ; infill
G1 X66.504 Y90.924 E143.94212 ; infill
G1 X52.076 Y76.496 E144.89137 ; infill
G1 X52.076 Y77.129 E144.92082 ; infill
G1 X65.871 Y90.924 E145.82843 ; infill
G1 X65.238 Y90.924 E145.85788 ; infill
G1 X52.076 Y77.762 E146.72384 ; infill
G1 X52.076 Y78.395 E146.75329 ; infill
G1 X64.605 Y90.924 E147.57761 ; infill
G1 X63.972 Y90.924 E147.60706 ; infill
G1 X52.076 Y79.028 E148.38974 ; infill
G1 X52.076 Y79.661 E148.41919 ; infill
G1 X63.339 Y90.924 E149.16023 ; infill
G1 X62.706 Y90.924 E149.18967 ; infill
G1 X52.076 Y80.294 E149.88907 ; infill
G1 X52.076 Y80.927 E149.91851 ; infill
G1 X62.073 Y90.924 E150.57626 ; infill
G1 X61.441 Y90.924 E150.60571 ; infill
G1 X52.076 Y81.559 E151.22182 ; infill
G1 X52.076 Y82.192 E151.25127 ; infill
G1 X60.808 Y90.924 E151.82573 ; infill
G1 X60.175 Y90.924 E151.85518 ; infill
G1 X52.076 Y82.825 E152.38800 ; infill
G1 X52.076 Y83.458 E152.41745 ; infill
G1 X59.542 Y90.924 E152.90863 ; infill
G1 X58.909 Y90.924 E152.93807 ; infill
G1 X52.076 Y84.091 E153.38761 ; infill
G1 X52.076 Y84.724 E153.41705 ; infill
G1 X58.276 Y90.924 E153.82495 ; infill
G1 X57.643 Y90.924 E153.85439 ; infill
G1 X52.076 Y85.357 E154.22064 ; infill
G1 X52.076 Y85.990 E154.25009 ; infill
G1 X57.010 Y90.924 E154.57470 ; infill
G1 X56.377 Y90.924 E154.60414 ; infill
G1 X52.076 Y86.623 E154.88711 ; infill
G1 X52.076 Y87.256 E154.91655 ; infill
G1 X55.744 Y90.924 E155.15787 ; infill
G1 X55.111 Y90.924 E155.18732 ; infill
G1 X52.076 Y87.889 E155.38700 ; infill
G1 X52.076 Y88.522 E155.41644 ; infill
G1 X54.478 Y90.924 E155.57448 ; infill
G1 X53.845 Y90.924 E155.60392 ; infill
G1 X52.076 Y89.155 E155.72031 ; infill
G1 X52.076 Y89.788 E155.74976 ; infill
G1 X53.212 Y90.924 E155.82451 ; infill
G1 X52.579 Y90.924 E155.85395 ; infill
G1 X51.875 Y90.220 E155.90027 ; infill
M104 S200 ; set temperature
M140 S65 ; set bed temperature
G1 E152.40027 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.500 F7500.000 ; move to next layer (1)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F2400
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F2160
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X89.315 Y91.225 F7500.000 ; move to first infill point
G1 E3.50000 F3000.00000 ; unretract
G1 F2400
G1 X90.024 Y90.516 E3.54689 ; infill
G1 X90.024 Y89.880 E3.57664 ; infill
G1 X88.880 Y91.024 E3.65233 ; infill
G1 X88.244 Y91.024 E3.68208 ; infill
G1 X90.024 Y89.244 E3.79985 ; infill
G1 X90.024 Y88.607 E3.82960 ; infill
G1 X87.607 Y91.024 E3.98944 ; infill
G1 X86.971 Y91.024 E4.01920 ; infill
G1 X90.024 Y87.971 E4.22112 ; infill
G1 X90.024 Y87.335 E4.25088 ; infill
G1 X86.335 Y91.024 E4.49488 ; infill
G1 X85.698 Y91.024 E4.52463 ; infill
G1 X90.024 Y86.698 E4.81071 ; infill
G1 X90.024 Y86.062 E4.84047 ; infill
G1 X85.062 Y91.024 E5.16863 ; infill
G1 X84.426 Y91.024 E5.19838 ; infill
G1 X90.024 Y85.426 E5.56862 ; infill
G1 X90.024 Y84.790 E5.59838 ; infill
G1 X83.790 Y91.024 E6.01070 ; infill
G1 X83.153 Y91.024 E6.04045 ; infill
G1 X90.024 Y84.153 E6.49485 ; infill
G1 X90.024 Y83.517 E6.52460 ; infill
G1 X82.517 Y91.024 E7.02108 ; infill
G1 X81.881 Y91.024 E7.05084 ; infill
G1 X90.024 Y82.881 E7.58939 ; infill
G1 X90.024 Y82.245 E7.61915 ; infill
G1 X81.245 Y91.024 E8.19978 ; infill
G1 X80.608 Y91.024 E8.22954 ; infill
G1 X90.024 Y81.608 E8.85225 ; infill
G1 X90.024 Y80.972 E8.88201 ; infill
G1 X79.972 Y91.024 E9.54680 ; infill
G1 X79.336 Y91.024 E9.57656 ; infill
G1 X90.024 Y80.336 E10.28343 ; infill
G1 X90.024 Y79.699 E10.31319 ; infill
G1 X78.699 Y91.024 E11.06214 ; infill
G1 X78.063 Y91.024 E11.09190 ; infill
G1 X90.024 Y79.063 E11.88293 ; infill
G1 X90.024 Y78.427 E11.91268 ; infill
G1 X77.427 Y91.024 E12.74580 ; infill
G1 X76.791 Y91.024 E12.77555 ; infill
G1 X90.024 Y77.791 E13.65074 ; infill
G1 X90.024 Y77.154 E13.68050 ; infill
G1 X76.154 Y91.024 E14.59777 ; infill
G1 X75.518 Y91.024 E14.62752 ; infill
G1 X90.024 Y76.518 E15.58687 ; infill
G1 X90.024 Y75.882 E15.61663 ; infill
G1 X74.882 Y91.024 E16.61806 ; infill
G1 X74.245 Y91.024 E16.64781 ; infill
G1 X90.024 Y75.245 E17.69132 ; infill
G1 X90.024 Y74.609 E17.72108 ; infill
G1 X73.609 Y91.024 E18.80666 ; infill
G1 X72.973 Y91.024 E18.83642 ; infill
G1 X90.024 Y73.973 E19.96409 ; infill
G1 X90.024 Y73.337 E19.99384 ; infill
G1 X72.337 Y91.024 E21.16359 ; infill
G1 X71.700 Y91.024 E21.19334 ; infill
G1 X90.024 Y72.700 E22.40517 ; infill
G1 X90.024 Y72.064 E22.43492 ; infill
G1 X71.064 Y91.024 E23.68883 ; infill
G1 X70.428 Y91.024 E23.71858 ; infill
G1 X90.024 Y71.428 E25.01457 ; infill
G1 X90.024 Y70.791 E25.04432 ; infill
G1 X69.791 Y91.024 E26.38239 ; infill
G1 X69.155 Y91.024 E26.41214 ; infill
G1 X90.024 Y70.155 E27.79229 ; infill
G1 X90.024 Y69.519 E27.82204 ; infill
G1 X68.519 Y91.024 E29.24427 ; infill
G1 X67.883 Y91.024 E29.27402 ; infill
G1 X90.024 Y68.883 E30.73832 ; infill
G1 X90.024 Y68.246 E30.76808 ; infill
G1 X67.246 Y91.024 E32.27446 ; infill
G1 X66.610 Y91.024 E32.30421 ; infill
G1 X90.024 Y67.610 E33.85267 ; infill
G1 X90.024 Y66.974 E33.88243 ; infill
G1 X65.974 Y91.024 E35.47297 ; infill
G1 X65.338 Y91.024 E35.50272 ; infill
G1 X90.024 Y66.338 E37.13534 ; infill
G1 X90.024 Y65.701 E37.16510 ; infill
G1 X64.701 Y91.024 E38.83980 ; infill
G1 X64.065 Y91.024 E38.86955 ; infill
G1 X90.024 Y65.065 E40.58633 ; infill
G1 X90.024 Y64.429 E40.61608 ; infill
G1 X63.429 Y91.024 E42.37494 ; infill
G1 X62.792 Y91.024 E42.40470 ; infill
G1 X90.024 Y63.792 E44.20563 ; infill
G1 X90.024 Y63.156 E44.23539 ; infill
G1 X62.156 Y91.024 E46.07841 ; infill
G1 X61.520 Y91.024 E46.10816 ; infill
G1 X90.024 Y62.520 E47.99326 ; infill
G1 X90.024 Y61.884 E48.02301 ; infill
G1 X60.884 Y91.024 E49.95019 ; infill
G1 X60.247 Y91.024 E49.97994 ; infill
G1 X90.024 Y61.247 E51.94919 ; infill
G1 X90.024 Y60.611 E51.97895 ; infill
G1 X59.611 Y91.024 E53.99028 ; infill
G1 X58.975 Y91.024 E54.02004 ; infill
G1 X90.024 Y59.975 E56.07345 ; infill
G1 X90.024 Y59.338 E56.10320 ; infill
G1 X58.338 Y91.024 E58.19870 ; infill
G1 X57.702 Y91.024 E58.22845 ; infill
G1 X90.024 Y58.702 E60.36602 ; infill
G1 X90.024 Y58.066 E60.39578 ; infill
G1 X57.066 Y91.024 E62.57543 ; infill
G1 X56.430 Y91.024 E62.60518 ; infill
G1 X90.024 Y57.430 E64.82691 ; infill
G1 X90.024 Y56.793 E64.85667 ; infill
G1 X55.793 Y91.024 E67.12048 ; infill
G1 X55.157 Y91.024 E67.15023 ; infill
G1 X90.024 Y56.157 E69.45612 ; infill
G1 X90.024 Y55.521 E69.48588 ; infill
G1 X54.521 Y91.024 E71.83385 ; infill
G1 X53.885 Y91.024 E71.86360 ; infill
G1 X90.024 Y54.885 E74.25365 ; infill
G1 X90.024 Y54.248 E74.28340 ; infill
G1 X53.248 Y91.024 E76.71553 ; infill
G1 X52.612 Y91.024 E76.74528 ; infill
G1 X90.024 Y53.612 E79.21949 ; infill
G1 X90.024 Y52.976 E79.24924 ; infill
G1 X51.976 Y91.024 E81.76553 ; infill
G1 X51.976 Y90.388 E81.79528 ; infill
G1 X89.388 Y52.976 E84.26948 ; infill
G1 X88.752 Y52.976 E84.29924 ; infill
G1 X51.976 Y89.752 E86.73136 ; infill
G1 X51.976 Y89.115 E86.76111 ; infill
G1 X88.115 Y52.976 E89.15116 ; infill
G1 X87.479 Y52.976 E89.18091 ; infill
G1 X51.976 Y88.479 E91.52888 ; infill
G1 X51.976 Y87.843 E91.55863 ; infill
G1 X86.843 Y52.976 E93.86451 ; infill
G1 X86.207 Y52.976 E93.89427 ; infill
G1 X51.976 Y87.207 E96.15807 ; infill
G1 X51.976 Y86.570 E96.18783 ; infill
G1 X85.570 Y52.976 E98.40955 ; infill
G1 X84.934 Y52.976 E98.43931 ; infill
G1 X51.976 Y85.934 E100.61896 ; infill
G1 X51.976 Y85.298 E100.64871 ; infill
G1 X84.298 Y52.976 E102.78628 ; infill
G1 X83.661 Y52.976 E102.81603 ; infill
G1 X51.976 Y84.661 E104.91152 ; infill
G1 X51.976 Y84.025 E104.94127 ; infill
G1 X83.025 Y52.976 E106.99468 ; infill
G1 X82.389 Y52.976 E107.02444 ; infill
G1 X51.976 Y83.389 E109.03577 ; infill
G1 X51.976 Y82.753 E109.06552 ; infill
G1 X81.753 Y52.976 E111.03477 ; infill
G1 X81.116 Y52.976 E111.06453 ; infill
G1 X51.976 Y82.116 E112.99170 ; infill
G1 X51.976 Y81.480 E113.02145 ; infill
G1 X80.480 Y52.976 E114.90654 ; infill
G1 X79.844 Y52.976 E114.93630 ; infill
G1 X51.976 Y80.844 E116.77931 ; infill
G1 X51.976 Y80.207 E116.80906 ; infill
G1 X79.208 Y52.976 E118.61000 ; infill
G1 X78.571 Y52.976 E118.63975 ; infill
G1 X51.976 Y79.571 E120.39860 ; infill
G1 X51.976 Y78.935 E120.42836 ; infill
G1 X77.935 Y52.976 E122.14513 ; infill
G1 X77.299 Y52.976 E122.17489 ; infill
G1 X51.976 Y78.299 E123.84958 ; infill
G1 X51.976 Y77.662 E123.87934 ; infill
G1 X76.662 Y52.976 E125.51195 ; infill
G1 X76.026 Y52.976 E125.54171 ; infill
G1 X51.976 Y77.026 E127.13224 ; infill
G1 X51.976 Y76.390 E127.16200 ; infill
G1 X75.390 Y52.976 E128.71045 ; infill
G1 X74.754 Y52.976 E128.74021 ; infill
G1 X51.976 Y75.754 E130.24658 ; infill
G1 X51.976 Y75.117 E130.27634 ; infill
G1 X74.117 Y52.976 E131.74064 ; infill
G1 X73.481 Y52.976 E131.77039 ; infill
G1 X51.976 Y74.481 E133.19261 ; infill
G1 X51.976 Y73.845 E133.22236 ; infill
G1 X72.845 Y52.976 E134.60250 ; infill
G1 X72.208 Y52.976 E134.63226 ; infill
G1 X51.976 Y73.208 E135.97032 ; infill
G1 X51.976 Y72.572 E136.00007 ; infill
G1 X71.572 Y52.976 E137.29605 ; infill
G1 X70.936 Y52.976 E137.32581 ; infill
G1 X51.976 Y71.936 E138.57971 ; infill
G1 X51.976 Y71.300 E138.60946 ; infill
G1 X70.300 Y52.976 E139.82129 ; infill
G1 X69.663 Y52.976 E139.85104 ; infill
G1 X51.976 Y70.663 E141.02078 ; infill
G1 X51.976 Y70.027 E141.05054 ; infill
G1 X69.027 Y52.976 E142.17820 ; infill
G1 X68.391 Y52.976 E142.20796 ; infill
G1 X51.976 Y69.391 E143.29354 ; infill
G1 X51.976 Y68.754 E143.32329 ; infill
G1 X67.754 Y52.976 E144.36680 ; infill
G1 X67.118 Y52.976 E144.39655 ; infill
G1 X51.976 Y68.118 E145.39798 ; infill
G1 X51.976 Y67.482 E145.42773 ; infill
G1 X66.482 Y52.976 E146.38708 ; infill
G1 X65.846 Y52.976 E146.41683 ; infill
G1 X51.976 Y66.846 E147.33410 ; infill
G1 X51.976 Y66.209 E147.36385 ; infill
G1 X65.209 Y52.976 E148.23904 ; infill
G1 X64.573 Y52.976 E148.26880 ; infill
G1 X51.976 Y65.573 E149.10190 ; infill
G1 X51.976 Y64.937 E149.13166 ; infill
G1 X63.937 Y52.976 E149.92269 ; infill
G1 X63.301 Y52.976 E149.95244 ; infill
G1 X51.976 Y64.301 E150.70139 ; infill
G1 X51.976 Y63.664 E150.73115 ; infill
G1 X62.664 Y52.976 E151.43802 ; infill
G1 X62.028 Y52.976 E151.46777 ; infill
G1 X51.976 Y63.028 E152.13256 ; infill
G1 X51.976 Y62.392 E152.16232 ; infill
G1 X61.392 Y52.976 E152.78503 ; infill
G1 X60.755 Y52.976 E152.81478 ; infill
G1 X51.976 Y61.755 E153.39541 ; infill
G1 X51.976 Y61.119 E153.42517 ; infill
G1 X60.119 Y52.976 E153.96372 ; infill
G1 X59.483 Y52.976 E153.99348 ; infill
G1 X51.976 Y60.483 E154.48995 ; infill
G1 X51.976 Y59.847 E154.51970 ; infill
G1 X58.847 Y52.976 E154.97410 ; infill
G1 X58.210 Y52.976 E155.00385 ; infill
G1 X51.976 Y59.210 E155.41617 ; infill
G1 X51.976 Y58.574 E155.44592 ; infill
G1 X57.574 Y52.976 E155.81616 ; infill
G1 X56.938 Y52.976 E155.84591 ; infill
G1 X51.976 Y57.938 E156.17407 ; infill
G1 X51.976 Y57.301 E156.20382 ; infill
G1 X56.301 Y52.976 E156.48990 ; infill
G1 X55.665 Y52.976 E156.51965 ; infill
G1 X51.976 Y56.665 E156.76365 ; infill
G1 X51.976 Y56.029 E156.79340 ; infill
G1 X55.029 Y52.976 E156.99532 ; infill
G1 X54.393 Y52.976 E157.02508 ; infill
G1 X51.976 Y55.393 E157.18492 ; infill
G1 X51.976 Y54.756 E157.21467 ; infill
G1 X53.756 Y52.976 E157.33243 ; infill
G1 X53.120 Y52.976 E157.36218 ; infill
G1 X51.976 Y54.120 E157.43786 ; infill
G1 X51.976 Y53.484 E157.46762 ; infill
G1 X52.685 Y52.775 E157.51450 ; infill
M106 S255 ; enable fan
G1 E154.01450 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z0.750 F7500.000 ; move to next layer (2)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.000 F7500.000 ; move to next layer (3)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.250 F7500.000 ; move to next layer (4)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.500 F7500.000 ; move to next layer (5)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.750 F7500.000 ; move to next layer (6)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.000 F7500.000 ; move to next layer (7)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.250 F7500.000 ; move to next layer (8)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.500 F7500.000 ; move to next layer (9)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z2.750 F7500.000 ; move to next layer (10)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.000 F7500.000 ; move to next layer (11)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.250 F7500.000 ; move to next layer (12)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.500 F7500.000 ; move to next layer (13)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z3.750 F7500.000 ; move to next layer (14)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.000 F7500.000 ; move to next layer (15)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.250 F7500.000 ; move to next layer (16)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.500 F7500.000 ; move to next layer (17)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z4.750 F7500.000 ; move to next layer (18)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z5.000 F7500.000 ; move to next layer (19)
G1 X90.404 Y91.404 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1655.35
G1 X51.596 Y91.404 E5.30037 ; perimeter
G1 X51.596 Y52.596 E7.10075 ; perimeter
G1 X90.404 Y52.596 E8.90112 ; perimeter
G1 X90.404 Y91.329 E10.69801 ; perimeter
G1 E7.19801 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
G1 X90.800 Y91.800 F7500.000 ; move to first perimeter point
G1 E3.50000 F3000.00000 ; unretract
G1 F1489.82
G1 X51.200 Y91.800 E4.92555 ; perimeter
G1 X51.200 Y52.200 E6.35111 ; perimeter
G1 X90.800 Y52.200 E7.77666 ; perimeter
G1 X90.800 Y91.725 E9.19952 ; perimeter
G1 X90.317 Y91.671 F7500.000 ; move inwards before travel
G1 E5.69952 F3000.00000 ; retract
G92 E0 ; reset extrusion distance
M107 ; disable fan
M140 S0 ; couper chauffe plateau
M104 S0 ; couper chauffe T0
G92 E0 ; reset extrudeur
G1 E-10 F3000 ; rétraction de 10mm
G1 X100 Y145 F1500 ; parking
G1 Z0 F3000
M84 ; couper moteurs
; filament used = 582.3mm (1.4cm3)
; filament used = 1.8g
; filament cost = 0.0
; total filament cost = 0.0

; avoid_crossing_perimeters = 0
; bed_shape = 12x2,130x2,130x142,12x142
; bed_temperature = 65
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 2
; duplicate_distance = 6
; end_gcode = M140 S0 ; couper chauffe plateau\nM104 S0 ; couper chauffe T0\nG92 E0 ; reset extrudeur\nG1 E-10 F3000 ; rétraction de 10mm\nG1 X100 Y145 F1500 ; parking\nG1 Z0 F3000\nM84 ; couper moteurs
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 1
; fan_below_layer_time = 30
; filament_colour = #00FF00
; filament_cost = 20
; filament_density = 1.25
; filament_diameter = 1.75
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 70
; first_layer_extrusion_width = 200%
; first_layer_speed = 50%
; first_layer_temperature = 195
; gcode_arcs = 0
; gcode_comments = 1
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_layer_height = 0.4
; max_print_speed = 60
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 15
; notes = Buse OEV5 - diamètre 0,5mm
; nozzle_diameter = 0.5
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base]_T0-500-250.gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 0.5
; retract_layer_change = 1
; retract_length = 3.5
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 50
; skirt_distance = 2
; skirt_height = 1
; skirts = 2
; slowdown_below_layer_time = 12
; spiral_vase = 0
; standby_temperature_delta = 0
; start_gcode = M190 S[first_layer_bed_temperature] ; attente chauffe plateau\nM104 S[first_layer_temperature] ; préchauffe tête\nG92 Z0\nG1 Z5 F1200\nG28 Y ; prise d'origine en Y\nG28 X ; prise d'origine en X\nG1 X70 Y70 F6000 ; parking\nM109 S[first_layer_temperature] ; attente chauffe T0
; temperature = 200
; threads = 2
; toolchange_gcode = 
; travel_speed = 125
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 0
; wipe = 0
; z_offset = 0
; clip_multipart_objects = 0
; dont_support_bridges = 1
; extrusion_width = 0.5
; first_layer_height = 0.25
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.25
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.5
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0.5
; support_material_interface_speed = 100%
; support_material_pattern = honeycomb
; support_material_spacing = 2
; support_material_speed = 40
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; xy_size_compensation = 0
; bottom_solid_layers = 2
; bridge_flow_ratio = 1
; bridge_speed = 40
; ensure_vertical_shell_thickness = 0
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0.4
; external_perimeter_speed = 90%
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 0%
; fill_pattern = honeycomb
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_overlap = 15%
; infill_speed = 40
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_speed = 40
; perimeters = 2
; small_perimeter_speed = 50%
; solid_infill_below_area = 9
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 40
; thin_walls = 1
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 90%
; top_solid_layers = 0
